### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by daianmartinho** [dmitrios/grafana-plugins-reftable#1]
First of all, thank you for your time working on this.

I'm trying to install your plugin but i can't see it on plugins list.

I'v moved reftable/ folder to /grafana/plugins/ and restarted the server without success.

**Comment by dmitrios** [comment]
Fixed in https://github.com/dmitrios/grafana-plugins-reftable/commit/dbb2a2d50ab18a2e9de773c1e1ae8ebc9ea03ece  @daianmartinho - please make sure you use Grafana version 4.1+ with this plugin.
