### ISSUE TITLE
[Feat Req]: retreiving the value of other column

### ISSUE THREAD

**Issue by genzo0101** [dmitrios/grafana-plugins-reftable#4]
Thanks for this plugin. I am expecting that I can get the value of other column. For example, column A has dashboard name and column B has the value of variable to pass to the dashboard. What I want to do is to create URL such as http://grafana_ip:3000/dashboard/db/columnA/var-varname=columnB

**Comment by dmitrios** [comment]
The latest changes in Grafana added support for multiple columns out of the box.
