### ISSUE TITLE
basic link from one dashboard to another

### ISSUE THREAD

**Issue by thatata** [dmitrios/grafana-plugins-reftable#5]
Hi dimitrios,

Thank you for making this plugin! I'm trying to add a simple link to another dashboard (modelstatus) in one specific column of my table, and as I read in other issues, the column disappears. My link looks something like: 

href="/dashboard/db/modelstatus?orgId=3"

Maybe I misunderstand the link usage example that you had in the README. I'm omitting any parameters in this example just to simply see the link to the other dashboard, modelstatus, but the column disappears.

Any help would be great!

**Comment by dmitrios** [comment]
As designed: The link will not be generated for the column that contains empty value.
